activities:
  -
    text: "Multi-armed bandit problem under delayed feedback: numerical experiments"
    date: 2020-02-14
    link: 'https://github.com/djo/delayed-bandit'
  -
    text: "Deep Learning Nanodegree Program"
    date: 2019-04-10
    link: '/assets/udacity-deep-learning-graduation.pdf'
  -
    text: "Circuit Breaker in Go based on sync/atomic"
    date: 2018-03-15
    link: 'https://github.com/djo/circuit'
  -
    text: "Machine Learning by Stanford University on Coursera"
    date: 2016-04-10
    link: 'https://coursera.org/verify/SHC9YW4FKDA7'
  -
    text: "Leader Election algorithm in Erlang"
    date: 2014-04-18
    link: 'https://github.com/Djo/leader_election'
  -
    text: "Algorithms in Ruby"
    date: 2013-12-08
    link: 'https://github.com/Djo/algorithms'
  -
    text: "Functional Programming Principles in Scala on Coursera"
    date: 2013-06-04
    link: '/assets/scala-certificate.pdf'
  -
    text: "HTTP Long Polling in Erlang and JavaScript"
    date: 2013-03-15
    link: 'https://github.com/Djo/kaede'
  -
    text: "Some solutions of Google Code Jam problems"
    date: 2013-02-26
    link: 'https://github.com/Djo/google-code-jam'
